### ISSUE TITLE
Search box webpart is not working on 23rd june 2020 onwards 

### ISSUE THREAD

**Issue by tony-philipose** [pnp/sp-dev-solutions#421]
> Use the following form to submit an issue only if it's related to samples in this repo. If you have an issue related to the SharePoint Framework or its documentation, please submit the issue at [https://github.com/SharePoint/sp-dev-docs/issues/new](https://github.com/SharePoint/sp-dev-docs/issues/new). This will help us respond to your issue faster.
> 
> ----
> 
> Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you.
> 
> _(DELETE THIS PARAGRAPH AFTER READING)_

#### Category
- [ ] Question
- [ ] Bug
- [x] Enhancement

> For the above list, an empty checkbox is [ ] as in <kbd>[</kbd><kbd>SPACE</kbd><kbd>]</kbd>. A checked checkbox is [x] with no space between the brackets. Use the `PREVIEW` tab at the top right to preview the rendering before submitting your issue.
> 
> _(DELETE THIS PARAGRAPH AFTER READING)_

#### Expected or Desired Behavior

> _If you are reporting a bug, please describe the expected behavior. If you are suggesting an enhancement please describe thoroughly the enhancement, how it can be achieved, and expected benefit._
> 
> _(DELETE THIS PARAGRAPH AFTER READING)_

#### Observed Behavior

> _If you are reporting a bug, please describe the behavior you expected to occur when performing the action. If you are making a suggestion, you can delete this section._
> 
> _(DELETE THIS PARAGRAPH AFTER READING)_

#### Steps to Reproduce

> _If you are reporting a bug please describe the steps to reproduce the bug in sufficient detail to allow testing. Only way to fix things properly, is to have sufficient details to reproduce it. If you are making a suggestion, you can delete this section._
> 
> _(DELETE THIS PARAGRAPH AFTER READING)_

#### Submission Guidelines

> - All suggestions or bugs are welcome, please let us know what's on your mind.
> - If you are reporting an issue around any of the samples, please ensure that you have clear reference on the sample and possibly code file, which should be fixed.
> - If you have technical questions about the framework, we’ll be monitoring #spfx, #spfx-webparts, and #spfx-tooling on (SharePoint StackExchange)> [http://sharepoint.stackexchange.com/]. You can also alternatively submit your question to (SharePoint Developer group)> [https://network.office.com/t5/SharePoint-Developer/bd-p/SharePointDev] at Office Network.
> - Remember to include sufficient details and context.
> - If you have multiple suggestions or bugs please submit them in separate bugs so we can track resolution.
> 
> _(DELETE THIS PARAGRAPH AFTER READING)_

Thanks for your contribution! Sharing is caring.

**Comment by Sachindagar** [comment]
We are also facing the same issue. It looks like there are some Search related changes push by MS to the tenant. We can see one advisory listed in the SharePoint health.


~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~`
User profile changes not reflected in search results within SharePoint Online
SP217039, SharePoint Online, Last updated: June 25, 2020 3:34 AM
**Start time: June 23, 2020 5:24 PM**
Status
Service degradation
User impact
User profile changes may not be reflected in search results within SharePoint Online.
Are you experiencing this issue?
Is this post helpful?
Latest message View history
Title: User profile changes not reflected in search results within SharePoint Online

User Impact: User profile changes may not be reflected in search results within SharePoint Online.

More info: Affected users can reach out to support to temporarily mitigate this issue through a manual re-crawl; however, changes made after the re-crawl will remain impacted.

Current status: We've developed a fix for the issue and are deploying it to the affected environments. Once the deployment completes, we’ll run a joblet to fully mitigate the issue. We anticipate the full mitigation will take approximately five days to complete.

Scope of impact: Any user may be impacted by this issue.

Root cause: A recent code change to the SharePoint Online service inadvertently resulted in impact.

Next update by: Friday, June 26, 2020, 5:30 AM (6/25/2020, 7:30 PM UTC)
